---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/gitlab.yml

  pre_tasks:
    - name: lint
      make:
        chdir: ../
        target: lint
      changed_when: false

    - name: log into docker registry
      community.general.docker_login:
        registry_url: registry.gitlab.com
        username: "{{ gitlab_username }}"
        password: "{{ gitlab_access_token }}"
  tasks:
    - name: build and push image-
      community.general.docker_image:
        build:
          path: ../
          pull: true
        name: registry.gitlab.com/registry-docker/teamiclink
        tag: 1.0.0
        force_source: true
        push: true
        source: build


